language: node_js
sudo: false
matrix:
  include:
    - node_js: "8"
    - node_js: "9"
    - node_js: "10"
    - node_js: "11"
    - node_js: "12"
  fast_finish: true
script:
  - "npm install"
  - "npm run lint"
  - "npm run test"
after_script: "npm run coverage"
